/*************************************
This program can be used to evaluate a jboost-trained classifier on new data.  
The code contains a single procedure:

  double predict(void **attr, double *ret)

The first argument attr is an array of pointers corresponding to the
attributes specified in the spec file.  Thus, if attribute i is text,
then attr[i] must be a char array; if attribute i is a number, then
*attr[i] must be a double; and if attribute i is finite, then *attr[i]
must be an int containing the index of the chosen value.  An undefined
attribute is indicated by setting attr[i] to NULL.

Specifically, these pointers are:

     index    attr.type    data.type   name
   ------------------------------------------
        0     number       double      word_freq_make
        1     number       double      word_freq_address
        2     number       double      word_freq_all
        3     number       double      word_freq_3d
        4     number       double      word_freq_our
        5     number       double      word_freq_over
        6     number       double      word_freq_remove
        7     number       double      word_freq_internet
        8     number       double      word_freq_order
        9     number       double      word_freq_mail
       10     number       double      word_freq_receive
       11     number       double      word_freq_will
       12     number       double      word_freq_people
       13     number       double      word_freq_report
       14     number       double      word_freq_addresses
       15     number       double      word_freq_free
       16     number       double      word_freq_business
       17     number       double      word_freq_email
       18     number       double      word_freq_you
       19     number       double      word_freq_credit
       20     number       double      word_freq_your
       21     number       double      word_freq_font
       22     number       double      word_freq_000
       23     number       double      word_freq_money
       24     number       double      word_freq_hp
       25     number       double      word_freq_hpl
       26     number       double      word_freq_george
       27     number       double      word_freq_650
       28     number       double      word_freq_lab
       29     number       double      word_freq_labs
       30     number       double      word_freq_telnet
       31     number       double      word_freq_857
       32     number       double      word_freq_data
       33     number       double      word_freq_415
       34     number       double      word_freq_85
       35     number       double      word_freq_technology
       36     number       double      word_freq_1999
       37     number       double      word_freq_parts
       38     number       double      word_freq_pm
       39     number       double      word_freq_direct
       40     number       double      word_freq_cs
       41     number       double      word_freq_meeting
       42     number       double      word_freq_original
       43     number       double      word_freq_project
       44     number       double      word_freq_re
       45     number       double      word_freq_edu
       46     number       double      word_freq_table
       47     number       double      word_freq_conference
       48     number       double      char_freq_semi
       49     number       double      char_freq_paren
       50     number       double      char_freq_bracket
       51     number       double      char_freq_bang
       52     number       double      char_freq_dollar
       53     number       double      char_freq_hash
       54     number       double      capital_run_length_average
       55     number       double      capital_run_length_longest
       56     number       double      capital_run_length_total

The second argument ret is a pointer to an array of k doubles, where k
is the number of classes.  The scores for each of the k classes will
be stored in this array.  If ret is NULL, then no scores are stored.
In any case, predict returns the score for class 0 (=ret[0]).

These scores correspond to the classes as follows:

            index       class name
           ------------------------
               0        +1
               1        -1

This classifier was automatically generated by jboost on
Mon Mar 19 20:05:39 CST 2012.
*************************************/
#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <values.h>
typedef double Prediction_t;
#define reset_pred()  {p = 0.0;}
#define add_pred(X) {p += (X);}
#define finalize_pred()  ((r) ? (r[1] = p , r[0] = -p) : -p)
#define defined_attr(X)  (attr[X])
#define int_attr(X)      (*((int *) attr[X]))
#define attr_contains_token(X,Y) (tokens[X][Y])
#define double_attr(X)   (*((double *) attr[X]))

#define WHITE_CHARS   " \t\n"
typedef struct hash_table_entry_s {
  char *key;
  int id;
  struct hash_table_entry_s *next;
} HashTableEntry_t;
static char *keys[] = {
};
#define num_keys  (0)
static HashTableEntry_t **hash_table = NULL;
#define hash_table_size  (1031)
static char *tokens[1];
static int text_attr[] = {};
#define num_text_attr  (0)
static char **text_patterns[] = {
};

static char **words;
static int num_words;
static int cur_word;
static char *pattern;
static int pattern_len;

static void set_pattern(int n, char **m_w, char *pat) {
  words = m_w;
  pattern = pat;
  cur_word = 0;
  num_words = n;
  pattern_len = strlen(pat);
}

#define more_tokens()  (cur_word <= num_words - pattern_len)

#define ADD_CHAR(S)  { \
  if (c >= buffer_size) { \
    buffer_size = 2 * buffer_size + 1; \
    buffer = (char *) realloc(buffer, buffer_size * sizeof(char)); \
  } \
  buffer[c++] = (S); \
}

static char *next_token(void) {
  static char *buffer = NULL;
  static int buffer_size = 0;
  int i, c;
  char *s;

  c = 0;
  for (s = pattern; *s; s++)
    ADD_CHAR(*s);

  for (i = 0; i < pattern_len; i++) {
    if (pattern[i] == '1') {
      ADD_CHAR(' ');
      for (s = words[cur_word + i]; *s; s++)
	ADD_CHAR(*s);
    }
  }
  ADD_CHAR('\0');
  cur_word++;
  return buffer;
}

static int
hash(char *s) {
  static int *coef = NULL;
  static int max_len = 0;
  int len = strlen(s);
  int i, h;

  if (len > max_len) {
    i = max_len;
    max_len = 2 * len;
    coef = (int *) realloc(coef, max_len * sizeof(int));
    for (; i < max_len; i++)
      coef[i] = random() % hash_table_size;
  }

  h = 0;
  for (i = 0; i < len; i++) {
     if (h >= MAXINT - (hash_table_size - 1) * 255)
       h = h % hash_table_size;
     h += coef[i] * s[i];
  }
  return (h % hash_table_size);
}

double predict(void **attr, double *r) {
  int i, j, h, a;
  HashTableEntry_t *entry;
  char *s;
  static char **words = NULL;
  static int max_word_list_size = 0;
  int num_words;
  static char *buffer = NULL;
  static int buffer_size = 0;
  char **pat;

  Prediction_t p;

  if (!hash_table) {
    hash_table = (HashTableEntry_t **)
      malloc(hash_table_size * sizeof(HashTableEntry_t *));
    for (i = 0; i < hash_table_size; i++)
      hash_table[i] = NULL;
    for (i = 0; i < num_keys; i++) {
      h = hash(keys[i]);
      entry = (HashTableEntry_t *) malloc(sizeof(HashTableEntry_t));
      entry->key = keys[i];
      entry->id = i;
      entry->next = hash_table[h];
      hash_table[h] = entry;
    }
    for (i = 0; i < num_text_attr; i++)
      tokens[text_attr[i]] = (char *) malloc(num_keys * sizeof(char));
  }

  for (i = 0; i < num_text_attr; i++) {
    a = text_attr[i];
    if (!defined_attr(a))
      continue;
    for (j = 0; j < num_keys; j++)
      tokens[a][j] = 0;

    while (strlcpy(buffer, attr[a], buffer_size) >= buffer_size) {
      buffer_size = 2 * strlen(attr[a]);
      buffer = (char *) realloc(buffer, (buffer_size+1) * sizeof(char));
    }
    num_words = 0;
    for (s = strtok(buffer, WHITE_CHARS); s; s = strtok(NULL, WHITE_CHARS)) {
      if (num_words >= max_word_list_size) {
        max_word_list_size = 2 * max_word_list_size + 1;
        words = (char **) realloc(words, max_word_list_size * sizeof(char *));
      }
      words[num_words++] = s;
    }
    for (pat = text_patterns[i]; *pat; pat++) {
      set_pattern(num_words, words, *pat);
      while (more_tokens()) {
        s = next_token();
        for (entry = hash_table[hash(s)]; entry; entry = entry->next)
          if (!strcmp(entry->key, s)) {
            tokens[a][entry->id] = 1;
            break;
          }
        }
      }
  }

  reset_pred();

  add_pred(   /* R */
             0.2279298102299376);
  if (defined_attr(51)) {  /* R.0 */
    if (double_attr(51) <= 0.0785) {
      add_pred(   /* R.0:0 */
                 0.638109949122525);
      if (defined_attr(26)) {  /* R.0:0.0 */
        if (double_attr(26) <= 0.0050) {
          add_pred(   /* R.0:0.0:0 */
                     -0.12718939476414323);
        } else {
          add_pred(   /* R.0:0.0:1 */
                     2.5542865876823897);
        }
      }
      if (defined_attr(25)) {  /* R.0:0.1 */
        if (double_attr(25) <= 0.12) {
          add_pred(   /* R.0:0.1:0 */
                     -0.04320076299937377);
        } else {
          add_pred(   /* R.0:0.1:1 */
                     1.195834392616679);
        }
      }
      if (defined_attr(11)) {  /* R.0:0.2 */
        if (double_attr(11) <= 2.09) {
          add_pred(   /* R.0:0.2:0 */
                     0.09047551473541447);
        } else {
          add_pred(   /* R.0:0.2:1 */
                     -0.9783080930113986);
        }
      }
    } else {
      add_pred(   /* R.0:1 */
                 -0.6921431150862234);
      if (defined_attr(51)) {  /* R.0:1.0 */
        if (double_attr(51) <= 0.8665) {
          add_pred(   /* R.0:1.0:0 */
                     0.3991238648063803);
          if (defined_attr(7)) {  /* R.0:1.0:0.0 */
            if (double_attr(7) <= 0.555) {
              add_pred(   /* R.0:1.0:0.0:0 */
                         0.13750659795245274);
              if (defined_attr(7)) {  /* R.0:1.0:0.0:0.0 */
                if (double_attr(7) <= 0.46499999999999997) {
                  add_pred(   /* R.0:1.0:0.0:0.0:0 */
                             0.02006811685673354);
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.0:1 */
                             1.7283709578806312);
                }
              }
              if (defined_attr(54)) {  /* R.0:1.0:0.0:0.1 */
                if (double_attr(54) <= 2.292) {
                  add_pred(   /* R.0:1.0:0.0:0.1:0 */
                             0.3769121096704494);
                } else {
                  add_pred(   /* R.0:1.0:0.0:0.1:1 */
                             -0.2815704554302351);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:0.0:1 */
                         -1.7360646941883031);
            }
          }
          if (defined_attr(20)) {  /* R.0:1.0:0.1 */
            if (double_attr(20) <= 0.895) {
              add_pred(   /* R.0:1.0:0.1:0 */
                         0.2731984314270501);
              if (defined_attr(9)) {  /* R.0:1.0:0.1:0.0 */
                if (double_attr(9) <= 0.165) {
                  add_pred(   /* R.0:1.0:0.1:0.0:0 */
                             0.2287634144283278);
                  if (defined_attr(18)) {  /* R.0:1.0:0.1:0.0:0.0 */
                    if (double_attr(18) <= 1.725) {
                      add_pred(   /* R.0:1.0:0.1:0.0:0.0:0 */
                                 -0.3073351142077014);
                    } else {
                      add_pred(   /* R.0:1.0:0.1:0.0:0.0:1 */
                                 0.5761871205481093);
                      if (defined_attr(18)) {  /* R.0:1.0:0.1:0.0:0.0:1.0 */
                        if (double_attr(18) <= 3.105) {
                          add_pred(   /* R.0:1.0:0.1:0.0:0.0:1.0:0 */
                                     1.15466753228499);
                        } else {
                          add_pred(   /* R.0:1.0:0.1:0.0:0.0:1.0:1 */
                                     -0.45867268138839296);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:0.1:0.0:1 */
                             -1.0800882527425142);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:0.1:1 */
                         -0.35235678265152803);
              if (defined_attr(56)) {  /* R.0:1.0:0.1:1.0 */
                if (double_attr(56) <= 41.5) {
                  add_pred(   /* R.0:1.0:0.1:1.0:0 */
                             0.8564374488069044);
                } else {
                  add_pred(   /* R.0:1.0:0.1:1.0:1 */
                             -0.4019101670352655);
                  if (defined_attr(22)) {  /* R.0:1.0:0.1:1.0:1.0 */
                    if (double_attr(22) <= 0.175) {
                      add_pred(   /* R.0:1.0:0.1:1.0:1.0:0 */
                                 -0.334961132288504);
                    } else {
                      add_pred(   /* R.0:1.0:0.1:1.0:1.0:1 */
                                 1.0753014220309358);
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.0:1.0:1 */
                     -0.446745208559594);
          if (defined_attr(9)) {  /* R.0:1.0:1.0 */
            if (double_attr(9) <= 0.665) {
              add_pred(   /* R.0:1.0:1.0:0 */
                         -0.6087832112436655);
              if (defined_attr(54)) {  /* R.0:1.0:1.0:0.0 */
                if (double_attr(54) <= 1.4060000000000001) {
                  add_pred(   /* R.0:1.0:1.0:0.0:0 */
                             0.8203743204161638);
                  if (defined_attr(56)) {  /* R.0:1.0:1.0:0.0:0.0 */
                    if (double_attr(56) <= 2.5) {
                      add_pred(   /* R.0:1.0:1.0:0.0:0.0:0 */
                                 -2.297560242675803);
                    } else {
                      add_pred(   /* R.0:1.0:1.0:0.0:0.0:1 */
                                 0.5935518968355185);
                    }
                  }
                } else {
                  add_pred(   /* R.0:1.0:1.0:0.0:1 */
                             -0.999900701703976);
                }
              }
            } else {
              add_pred(   /* R.0:1.0:1.0:1 */
                         0.7995620739555858);
            }
          }
        }
      }
      if (defined_attr(8)) {  /* R.0:1.1 */
        if (double_attr(8) <= 0.745) {
          add_pred(   /* R.0:1.1:0 */
                     0.20604687020488657);
        } else {
          add_pred(   /* R.0:1.1:1 */
                     -2.3138890605727656);
        }
      }
    }
  }
  if (defined_attr(6)) {  /* R.1 */
    if (double_attr(6) <= 0.01) {
      add_pred(   /* R.1:0 */
                 0.2596893350510752);
      if (defined_attr(24)) {  /* R.1:0.0 */
        if (double_attr(24) <= 0.12) {
          add_pred(   /* R.1:0.0:0 */
                     -0.1824859290693248);
          if (defined_attr(55)) {  /* R.1:0.0:0.0 */
            if (double_attr(55) <= 9.5) {
              add_pred(   /* R.1:0.0:0.0:0 */
                         0.650314251446431);
              if (defined_attr(18)) {  /* R.1:0.0:0.0:0.0 */
                if (double_attr(18) <= 1.915) {
                  add_pred(   /* R.1:0.0:0.0:0.0:0 */
                             0.3626448002472613);
                  if (defined_attr(54)) {  /* R.1:0.0:0.0:0.0:0.0 */
                    if (double_attr(54) <= 1.4775) {
                      add_pred(   /* R.1:0.0:0.0:0.0:0.0:0 */
                                 -0.38047298964725335);
                      if (defined_attr(11)) {  /* R.1:0.0:0.0:0.0:0.0:0.0 */
                        if (double_attr(11) <= 0.59) {
                          add_pred(   /* R.1:0.0:0.0:0.0:0.0:0.0:0 */
                                     -0.051079758792213735);
                          if (defined_attr(56)) {  /* R.1:0.0:0.0:0.0:0.0:0.0:0.0 */
                            if (double_attr(56) <= 5.5) {
                              add_pred(   /* R.1:0.0:0.0:0.0:0.0:0.0:0.0:0 */
                                         1.3439420012434045);
                              if (defined_attr(51)) {  /* R.1:0.0:0.0:0.0:0.0:0.0:0.0:0.0 */
                                if (double_attr(51) <= 3.8035) {
                                  add_pred(   /* R.1:0.0:0.0:0.0:0.0:0.0:0.0:0.0:0 */
                                             1.9996326322774056);
                                } else {
                                  add_pred(   /* R.1:0.0:0.0:0.0:0.0:0.0:0.0:0.0:1 */
                                             -1.898502632288497);
                                }
                              }
                            } else {
                              add_pred(   /* R.1:0.0:0.0:0.0:0.0:0.0:0.0:1 */
                                         -0.28443133405072657);
                            }
                          }
                        } else {
                          add_pred(   /* R.1:0.0:0.0:0.0:0.0:0.0:1 */
                                     2.4054092270941294);
                        }
                      }
                    } else {
                      add_pred(   /* R.1:0.0:0.0:0.0:0.0:1 */
                                 0.8969288515733932);
                      if (defined_attr(15)) {  /* R.1:0.0:0.0:0.0:0.0:1.0 */
                        if (double_attr(15) <= 0.14) {
                          add_pred(   /* R.1:0.0:0.0:0.0:0.0:1.0:0 */
                                     1.0464833282962616);
                          if (defined_attr(54)) {  /* R.1:0.0:0.0:0.0:0.0:1.0:0.0 */
                            if (double_attr(54) <= 3.7915) {
                              add_pred(   /* R.1:0.0:0.0:0.0:0.0:1.0:0.0:0 */
                                         2.3640407509750716);
                            } else {
                              add_pred(   /* R.1:0.0:0.0:0.0:0.0:1.0:0.0:1 */
                                         -0.720950896277365);
                            }
                          }
                        } else {
                          add_pred(   /* R.1:0.0:0.0:0.0:0.0:1.0:1 */
                                     -0.8592398915902519);
                        }
                      }
                    }
                  }
                  if (defined_attr(56)) {  /* R.1:0.0:0.0:0.0:0.1 */
                    if (double_attr(56) <= 18.5) {
                      add_pred(   /* R.1:0.0:0.0:0.0:0.1:0 */
                                 0.4765504893694142);
                    } else {
                      add_pred(   /* R.1:0.0:0.0:0.0:0.1:1 */
                                 -0.38707983303520754);
                      if (defined_attr(44)) {  /* R.1:0.0:0.0:0.0:0.1:1.0 */
                        if (double_attr(44) <= 0.04) {
                          add_pred(   /* R.1:0.0:0.0:0.0:0.1:1.0:0 */
                                     -0.35236029710281397);
                        } else {
                          add_pred(   /* R.1:0.0:0.0:0.0:0.1:1.0:1 */
                                     2.5354101849539386);
                        }
                      }
                    }
                  }
                } else {
                  add_pred(   /* R.1:0.0:0.0:0.0:1 */
                             -0.22141540123491726);
                  if (defined_attr(49)) {  /* R.1:0.0:0.0:0.0:1.0 */
                    if (double_attr(49) <= 0.1865) {
                      add_pred(   /* R.1:0.0:0.0:0.0:1.0:0 */
                                 -0.1567005340938676);
                      if (defined_attr(18)) {  /* R.1:0.0:0.0:0.0:1.0:0.0 */
                        if (double_attr(18) <= 1.97) {
                          add_pred(   /* R.1:0.0:0.0:0.0:1.0:0.0:0 */
                                     -1.4186732234033455);
                        } else {
                          add_pred(   /* R.1:0.0:0.0:0.0:1.0:0.0:1 */
                                     0.12946942093515165);
                        }
                      }
                    } else {
                      add_pred(   /* R.1:0.0:0.0:0.0:1.0:1 */
                                 1.8070541583025976);
                    }
                  }
                }
              }
              if (defined_attr(5)) {  /* R.1:0.0:0.0:0.1 */
                if (double_attr(5) <= 0.165) {
                  add_pred(   /* R.1:0.0:0.0:0.1:0 */
                             -0.04038813276740411);
                } else {
                  add_pred(   /* R.1:0.0:0.0:0.1:1 */
                             1.7624338116149687);
                }
              }
            } else {
              add_pred(   /* R.1:0.0:0.0:1 */
                         -0.37794712925536966);
              if (defined_attr(36)) {  /* R.1:0.0:0.0:1.0 */
                if (double_attr(36) <= 0.155) {
                  add_pred(   /* R.1:0.0:0.0:1.0:0 */
                             -0.319968268624635);
                  if (defined_attr(54)) {  /* R.1:0.0:0.0:1.0:0.0 */
                    if (double_attr(54) <= 1.9355) {
                      add_pred(   /* R.1:0.0:0.0:1.0:0.0:0 */
                                 0.758229343165233);
                      if (defined_attr(42)) {  /* R.1:0.0:0.0:1.0:0.0:0.0 */
                        if (double_attr(42) <= 0.03) {
                          add_pred(   /* R.1:0.0:0.0:1.0:0.0:0.0:0 */
                                     0.40510797247408553);
                        } else {
                          add_pred(   /* R.1:0.0:0.0:1.0:0.0:0.0:1 */
                                     -1.9246635284933735);
                        }
                      }
                    } else {
                      add_pred(   /* R.1:0.0:0.0:1.0:0.0:1 */
                                 -0.16513319230305792);
                      if (defined_attr(18)) {  /* R.1:0.0:0.0:1.0:0.0:1.0 */
                        if (double_attr(18) <= 6.039999999999999) {
                          add_pred(   /* R.1:0.0:0.0:1.0:0.0:1.0:0 */
                                     0.09738871284967826);
                        } else {
                          add_pred(   /* R.1:0.0:0.0:1.0:0.0:1.0:1 */
                                     -2.1750961499223602);
                        }
                      }
                    }
                  }
                  if (defined_attr(52)) {  /* R.1:0.0:0.0:1.0:0.1 */
                    if (double_attr(52) <= 0.013000000000000001) {
                      add_pred(   /* R.1:0.0:0.0:1.0:0.1:0 */
                                 0.2038710187734347);
                    } else {
                      add_pred(   /* R.1:0.0:0.0:1.0:0.1:1 */
                                 -0.46353537014146745);
                    }
                  }
                } else {
                  add_pred(   /* R.1:0.0:0.0:1.0:1 */
                             0.9158270298536499);
                }
              }
              if (defined_attr(22)) {  /* R.1:0.0:0.0:1.1 */
                if (double_attr(22) <= 0.485) {
                  add_pred(   /* R.1:0.0:0.0:1.1:0 */
                             0.07089149507910353);
                } else {
                  add_pred(   /* R.1:0.0:0.0:1.1:1 */
                             -2.49716134423075);
                }
              }
              if (defined_attr(11)) {  /* R.1:0.0:0.0:1.2 */
                if (double_attr(11) <= 1.9249999999999998) {
                  add_pred(   /* R.1:0.0:0.0:1.2:0 */
                             -0.08176661589609413);
                } else {
                  add_pred(   /* R.1:0.0:0.0:1.2:1 */
                             1.0133515027912412);
                  if (defined_attr(18)) {  /* R.1:0.0:0.0:1.2:1.0 */
                    if (double_attr(18) <= 2.335) {
                      add_pred(   /* R.1:0.0:0.0:1.2:1.0:0 */
                                 1.9488443928193033);
                    } else {
                      add_pred(   /* R.1:0.0:0.0:1.2:1.0:1 */
                                 -0.6463502732100044);
                    }
                  }
                }
              }
              if (defined_attr(5)) {  /* R.1:0.0:0.0:1.3 */
                if (double_attr(5) <= 0.235) {
                  add_pred(   /* R.1:0.0:0.0:1.3:0 */
                             0.10092347527904473);
                } else {
                  add_pred(   /* R.1:0.0:0.0:1.3:1 */
                             -0.8384834081776503);
                  if (defined_attr(42)) {  /* R.1:0.0:0.0:1.3:1.0 */
                    if (double_attr(42) <= 0.25) {
                      add_pred(   /* R.1:0.0:0.0:1.3:1.0:0 */
                                 -0.7179543608247978);
                    } else {
                      add_pred(   /* R.1:0.0:0.0:1.3:1.0:1 */
                                 2.3506473106996335);
                    }
                  }
                }
              }
            }
          }
          if (defined_attr(16)) {  /* R.1:0.0:0.1 */
            if (double_attr(16) <= 0.095) {
              add_pred(   /* R.1:0.0:0.1:0 */
                         0.07651383094496837);
              if (defined_attr(54)) {  /* R.1:0.0:0.1:0.0 */
                if (double_attr(54) <= 3.4835000000000003) {
                  add_pred(   /* R.1:0.0:0.1:0.0:0 */
                             0.17220583704808362);
                } else {
                  add_pred(   /* R.1:0.0:0.1:0.0:1 */
                             -0.3831884308414989);
                  if (defined_attr(51)) {  /* R.1:0.0:0.1:0.0:1.0 */
                    if (double_attr(51) <= 0.6675) {
                      add_pred(   /* R.1:0.0:0.1:0.0:1.0:0 */
                                 0.03976788062761522);
                    } else {
                      add_pred(   /* R.1:0.0:0.1:0.0:1.0:1 */
                                 -2.1294992076320822);
                    }
                  }
                  if (defined_attr(44)) {  /* R.1:0.0:0.1:0.0:1.1 */
                    if (double_attr(44) <= 0.865) {
                      add_pred(   /* R.1:0.0:0.1:0.0:1.1:0 */
                                 -0.1005430633186593);
                    } else {
                      add_pred(   /* R.1:0.0:0.1:0.0:1.1:1 */
                                 -2.363403366882297);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.1:0.0:0.1:1 */
                         -0.7035209749842959);
            }
          }
        } else {
          add_pred(   /* R.1:0.0:1 */
                     1.0952082453519383);
          if (defined_attr(10)) {  /* R.1:0.0:1.0 */
            if (double_attr(10) <= 0.94) {
              add_pred(   /* R.1:0.0:1.0:0 */
                         0.16748387354117275);
              if (defined_attr(11)) {  /* R.1:0.0:1.0:0.0 */
                if (double_attr(11) <= 0.10500000000000001) {
                  add_pred(   /* R.1:0.0:1.0:0.0:0 */
                             -0.6251218457017379);
                  if (defined_attr(15)) {  /* R.1:0.0:1.0:0.0:0.0 */
                    if (double_attr(15) <= 0.015) {
                      add_pred(   /* R.1:0.0:1.0:0.0:0.0:0 */
                                 0.4925704886612749);
                      if (defined_attr(32)) {  /* R.1:0.0:1.0:0.0:0.0:0.0 */
                        if (double_attr(32) <= 1.02) {
                          add_pred(   /* R.1:0.0:1.0:0.0:0.0:0.0:0 */
                                     2.027683560444748);
                        } else {
                          add_pred(   /* R.1:0.0:1.0:0.0:0.0:0.0:1 */
                                     -1.4404363975708323);
                        }
                      }
                    } else {
                      add_pred(   /* R.1:0.0:1.0:0.0:0.0:1 */
                                 -1.6977499906603697);
                    }
                  }
                } else {
                  add_pred(   /* R.1:0.0:1.0:0.0:1 */
                             0.869255288569001);
                  if (defined_attr(48)) {  /* R.1:0.0:1.0:0.0:1.0 */
                    if (double_attr(48) <= 0.0715) {
                      add_pred(   /* R.1:0.0:1.0:0.0:1.0:0 */
                                 1.988871150743556);
                    } else {
                      add_pred(   /* R.1:0.0:1.0:0.0:1.0:1 */
                                 -0.4925809789959755);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.1:0.0:1.0:1 */
                         -2.5142450938489413);
            }
          }
          if (defined_attr(29)) {  /* R.1:0.0:1.1 */
            if (double_attr(29) <= 0.025) {
              add_pred(   /* R.1:0.0:1.1:0 */
                         -0.1754011586248014);
            } else {
              add_pred(   /* R.1:0.0:1.1:1 */
                         2.3975489251550703);
            }
          }
        }
      }
      if (defined_attr(41)) {  /* R.1:0.1 */
        if (double_attr(41) <= 0.455) {
          add_pred(   /* R.1:0.1:0 */
                     -0.07375891128821287);
          if (defined_attr(4)) {  /* R.1:0.1:0.0 */
            if (double_attr(4) <= 0.095) {
              add_pred(   /* R.1:0.1:0.0:0 */
                         0.2083470537391964);
              if (defined_attr(55)) {  /* R.1:0.1:0.0:0.0 */
                if (double_attr(55) <= 46.5) {
                  add_pred(   /* R.1:0.1:0.0:0.0:0 */
                             -0.002479084315754684);
                } else {
                  add_pred(   /* R.1:0.1:0.0:0.0:1 */
                             0.7169691357474665);
                  if (defined_attr(13)) {  /* R.1:0.1:0.0:0.0:1.0 */
                    if (double_attr(13) <= 0.7949999999999999) {
                      add_pred(   /* R.1:0.1:0.0:0.0:1.0:0 */
                                 0.6703173138082369);
                    } else {
                      add_pred(   /* R.1:0.1:0.0:0.0:1.0:1 */
                                 -1.9617691747762789);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.1:0.1:0.0:1 */
                         -0.49170630741860094);
              if (defined_attr(17)) {  /* R.1:0.1:0.0:1.0 */
                if (double_attr(17) <= 0.435) {
                  add_pred(   /* R.1:0.1:0.0:1.0:0 */
                             0.05495579184983785);
                  if (defined_attr(15)) {  /* R.1:0.1:0.0:1.0:0.0 */
                    if (double_attr(15) <= 0.235) {
                      add_pred(   /* R.1:0.1:0.0:1.0:0.0:0 */
                                 0.19546933447861753);
                    } else {
                      add_pred(   /* R.1:0.1:0.0:1.0:0.0:1 */
                                 -0.871803181097489);
                    }
                  }
                } else {
                  add_pred(   /* R.1:0.1:0.0:1.0:1 */
                             -1.102402027976989);
                  if (defined_attr(17)) {  /* R.1:0.1:0.0:1.0:1.0 */
                    if (double_attr(17) <= 1.14) {
                      add_pred(   /* R.1:0.1:0.0:1.0:1.0:0 */
                                 -1.3524043158527201);
                    } else {
                      add_pred(   /* R.1:0.1:0.0:1.0:1.0:1 */
                                 0.957816672409687);
                    }
                  }
                }
              }
            }
          }
        } else {
          add_pred(   /* R.1:0.1:1 */
                     2.891129212121895);
        }
      }
      if (defined_attr(24)) {  /* R.1:0.2 */
        if (double_attr(24) <= 2.065) {
          add_pred(   /* R.1:0.2:0 */
                     -0.02473171972751506);
          if (defined_attr(43)) {  /* R.1:0.2:0.0 */
            if (double_attr(43) <= 0.035) {
              add_pred(   /* R.1:0.2:0.0:0 */
                         -0.06988699532624541);
              if (defined_attr(19)) {  /* R.1:0.2:0.0:0.0 */
                if (double_attr(19) <= 0.725) {
                  add_pred(   /* R.1:0.2:0.0:0.0:0 */
                             0.042090205363169535);
                } else {
                  add_pred(   /* R.1:0.2:0.0:0.0:1 */
                             -2.491304896895637);
                }
              }
            } else {
              add_pred(   /* R.1:0.2:0.0:1 */
                         1.2531229702103839);
            }
          }
        } else {
          add_pred(   /* R.1:0.2:1 */
                     2.605278006141917);
        }
      }
    } else {
      add_pred(   /* R.1:1 */
                 -1.5319957375187236);
      if (defined_attr(20)) {  /* R.1:1.0 */
        if (double_attr(20) <= 0.46499999999999997) {
          add_pred(   /* R.1:1.0:0 */
                     0.45882238456832625);
          if (defined_attr(7)) {  /* R.1:1.0:0.0 */
            if (double_attr(7) <= 0.96) {
              add_pred(   /* R.1:1.0:0.0:0 */
                         -0.3045902815112866);
              if (defined_attr(55)) {  /* R.1:1.0:0.0:0.0 */
                if (double_attr(55) <= 7.0) {
                  add_pred(   /* R.1:1.0:0.0:0.0:0 */
                             1.5085779254752623);
                } else {
                  add_pred(   /* R.1:1.0:0.0:0.0:1 */
                             -0.5719058283506544);
                }
              }
            } else {
              add_pred(   /* R.1:1.0:0.0:1 */
                         2.2945815512963903);
            }
          }
        } else {
          add_pred(   /* R.1:1.0:1 */
                     -0.5605088709134939);
          if (defined_attr(20)) {  /* R.1:1.0:1.0 */
            if (double_attr(20) <= 3.36) {
              add_pred(   /* R.1:1.0:1.0:0 */
                         -0.47929060656831235);
            } else {
              add_pred(   /* R.1:1.0:1.0:1 */
                         1.5620867611077849);
            }
          }
        }
      }
      if (defined_attr(12)) {  /* R.1:1.1 */
        if (double_attr(12) <= 0.255) {
          add_pred(   /* R.1:1.1:0 */
                     -0.16113703588118913);
        } else {
          add_pred(   /* R.1:1.1:1 */
                     -2.362998853454286);
        }
      }
    }
  }
  if (defined_attr(52)) {  /* R.2 */
    if (double_attr(52) <= 0.1035) {
      add_pred(   /* R.2:0 */
                 0.2247157914956868);
      if (defined_attr(15)) {  /* R.2:0.0 */
        if (double_attr(15) <= 0.415) {
          add_pred(   /* R.2:0.0:0 */
                     0.08840525424025716);
          if (defined_attr(44)) {  /* R.2:0.0:0.0 */
            if (double_attr(44) <= 0.805) {
              add_pred(   /* R.2:0.0:0.0:0 */
                         -0.07611798946037451);
              if (defined_attr(47)) {  /* R.2:0.0:0.0:0.0 */
                if (double_attr(47) <= 0.27) {
                  add_pred(   /* R.2:0.0:0.0:0.0:0 */
                             -0.012463588501227467);
                } else {
                  add_pred(   /* R.2:0.0:0.0:0.0:1 */
                             2.3729539648874036);
                }
              }
            } else {
              add_pred(   /* R.2:0.0:0.0:1 */
                         1.4153905475016844);
              if (defined_attr(19)) {  /* R.2:0.0:0.0:1.0 */
                if (double_attr(19) <= 0.225) {
                  add_pred(   /* R.2:0.0:0.0:1.0:0 */
                             0.6430508433310332);
                  if (defined_attr(16)) {  /* R.2:0.0:0.0:1.0:0.0 */
                    if (double_attr(16) <= 0.515) {
                      add_pred(   /* R.2:0.0:0.0:1.0:0.0:0 */
                                 1.7165255350307436);
                    } else {
                      add_pred(   /* R.2:0.0:0.0:1.0:0.0:1 */
                                 -1.2293214242967803);
                    }
                  }
                } else {
                  add_pred(   /* R.2:0.0:0.0:1.0:1 */
                             -2.1323030897401343);
                }
              }
            }
          }
        } else {
          add_pred(   /* R.2:0.0:1 */
                     -0.6187969575719631);
          if (defined_attr(54)) {  /* R.2:0.0:1.0 */
            if (double_attr(54) <= 1.7965) {
              add_pred(   /* R.2:0.0:1.0:0 */
                         -0.9112471882667126);
            } else {
              add_pred(   /* R.2:0.0:1.0:1 */
                         0.22898650179423238);
              if (defined_attr(17)) {  /* R.2:0.0:1.0:1.0 */
                if (double_attr(17) <= 1.6549999999999998) {
                  add_pred(   /* R.2:0.0:1.0:1.0:0 */
                             -0.044676731891435666);
                } else {
                  add_pred(   /* R.2:0.0:1.0:1.0:1 */
                             1.7693418208891067);
                }
              }
              if (defined_attr(56)) {  /* R.2:0.0:1.0:1.1 */
                if (double_attr(56) <= 38.0) {
                  add_pred(   /* R.2:0.0:1.0:1.1:0 */
                             -2.2492749915916583);
                } else {
                  add_pred(   /* R.2:0.0:1.0:1.1:1 */
                             0.2382659985524544);
                }
              }
            }
          }
          if (defined_attr(9)) {  /* R.2:0.0:1.1 */
            if (double_attr(9) <= 1.06) {
              add_pred(   /* R.2:0.0:1.1:0 */
                         -0.22014715553082245);
              if (defined_attr(6)) {  /* R.2:0.0:1.1:0.0 */
                if (double_attr(6) <= 0.03) {
                  add_pred(   /* R.2:0.0:1.1:0.0:0 */
                             0.14861537838406003);
                } else {
                  add_pred(   /* R.2:0.0:1.1:0.0:1 */
                             -2.4166170421325908);
                }
              }
            } else {
              add_pred(   /* R.2:0.0:1.1:1 */
                         1.1864518098251529);
            }
          }
        }
      }
      if (defined_attr(48)) {  /* R.2:0.1 */
        if (double_attr(48) <= 0.464) {
          add_pred(   /* R.2:0.1:0 */
                     -0.057082028286136566);
          if (defined_attr(21)) {  /* R.2:0.1:0.0 */
            if (double_attr(21) <= 0.135) {
              add_pred(   /* R.2:0.1:0.0:0 */
                         -0.030315673607414922);
            } else {
              add_pred(   /* R.2:0.1:0.0:1 */
                         -2.2969327587942225);
            }
          }
          if (defined_attr(36)) {  /* R.2:0.1:0.1 */
            if (double_attr(36) <= 0.155) {
              add_pred(   /* R.2:0.1:0.1:0 */
                         -0.10502640437350072);
              if (defined_attr(3)) {  /* R.2:0.1:0.1:0.0 */
                if (double_attr(3) <= 0.365) {
                  add_pred(   /* R.2:0.1:0.1:0.0:0 */
                             -0.006215429389537978);
                } else {
                  add_pred(   /* R.2:0.1:0.1:0.0:1 */
                             -2.366915064145462);
                }
              }
            } else {
              add_pred(   /* R.2:0.1:0.1:1 */
                         0.693790227487584);
            }
          }
        } else {
          add_pred(   /* R.2:0.1:1 */
                     2.4221248493995775);
        }
      }
    } else {
      add_pred(   /* R.2:1 */
                 -1.1253547454397437);
      if (defined_attr(56)) {  /* R.2:1.0 */
        if (double_attr(56) <= 205.0) {
          add_pred(   /* R.2:1.0:0 */
                     0.4031625324318607);
          if (defined_attr(18)) {  /* R.2:1.0:0.0 */
            if (double_attr(18) <= 4.375) {
              add_pred(   /* R.2:1.0:0.0:0 */
                         0.2996184280156841);
            } else {
              add_pred(   /* R.2:1.0:0.0:1 */
                         -2.2303931141183937);
            }
          }
        } else {
          add_pred(   /* R.2:1.0:1 */
                     -1.2388338294837038);
        }
      }
    }
  }
  if (defined_attr(26)) {  /* R.3 */
    if (double_attr(26) <= 0.20500000000000002) {
      add_pred(   /* R.3:0 */
                 -0.12867236787515568);
      if (defined_attr(45)) {  /* R.3:0.0 */
        if (double_attr(45) <= 0.08499999999999999) {
          add_pred(   /* R.3:0.0:0 */
                     -0.1356172545899705);
          if (defined_attr(28)) {  /* R.3:0.0:0.0 */
            if (double_attr(28) <= 0.07) {
              add_pred(   /* R.3:0.0:0.0:0 */
                         -0.05130492037592239);
            } else {
              add_pred(   /* R.3:0.0:0.0:1 */
                         2.4997488464068782);
            }
          }
          if (defined_attr(23)) {  /* R.3:0.0:0.1 */
            if (double_attr(23) <= 1.045) {
              add_pred(   /* R.3:0.0:0.1:0 */
                         0.0110606178295198);
              if (defined_attr(56)) {  /* R.3:0.0:0.1:0.0 */
                if (double_attr(56) <= 896.5) {
                  add_pred(   /* R.3:0.0:0.1:0.0:0 */
                             0.012659096266160895);
                } else {
                  add_pred(   /* R.3:0.0:0.1:0.0:1 */
                             -1.0504754684734277);
                  if (defined_attr(34)) {  /* R.3:0.0:0.1:0.0:1.0 */
                    if (double_attr(34) <= 0.07500000000000001) {
                      add_pred(   /* R.3:0.0:0.1:0.0:1.0:0 */
                                 -1.0950794452127872);
                    } else {
                      add_pred(   /* R.3:0.0:0.1:0.0:1.0:1 */
                                 1.8115026207159148);
                    }
                  }
                }
              }
              if (defined_attr(4)) {  /* R.3:0.0:0.1:0.1 */
                if (double_attr(4) <= 1.065) {
                  add_pred(   /* R.3:0.0:0.1:0.1:0 */
                             0.03388970740525111);
                } else {
                  add_pred(   /* R.3:0.0:0.1:0.1:1 */
                             -0.6811540851841823);
                }
              }
              if (defined_attr(22)) {  /* R.3:0.0:0.1:0.2 */
                if (double_attr(22) <= 0.245) {
                  add_pred(   /* R.3:0.0:0.1:0.2:0 */
                             0.019515125882344938);
                } else {
                  add_pred(   /* R.3:0.0:0.1:0.2:1 */
                             -1.0904562117971728);
                  if (defined_attr(8)) {  /* R.3:0.0:0.1:0.2:1.0 */
                    if (double_attr(8) <= 0.475) {
                      add_pred(   /* R.3:0.0:0.1:0.2:1.0:0 */
                                 -1.3749727660447102);
                    } else {
                      add_pred(   /* R.3:0.0:0.1:0.2:1.0:1 */
                                 1.3500706205341997);
                    }
                  }
                }
              }
            } else {
              add_pred(   /* R.3:0.0:0.1:1 */
                         -1.8162624555651379);
            }
          }
        } else {
          add_pred(   /* R.3:0.0:1 */
                     1.0192628791621654);
          if (defined_attr(27)) {  /* R.3:0.0:1.0 */
            if (double_attr(27) <= 0.22999999999999998) {
              add_pred(   /* R.3:0.0:1.0:0 */
                         0.4300075533514173);
              if (defined_attr(11)) {  /* R.3:0.0:1.0:0.0 */
                if (double_attr(11) <= 2.2800000000000002) {
                  add_pred(   /* R.3:0.0:1.0:0.0:0 */
                             0.45789540114384236);
                  if (defined_attr(18)) {  /* R.3:0.0:1.0:0.0:0.0 */
                    if (double_attr(18) <= 0.0050) {
                      add_pred(   /* R.3:0.0:1.0:0.0:0.0:0 */
                                 -0.6443983745258496);
                    } else {
                      add_pred(   /* R.3:0.0:1.0:0.0:0.0:1 */
                                 1.1792295869562015);
                    }
                  }
                  if (defined_attr(49)) {  /* R.3:0.0:1.0:0.0:0.1 */
                    if (double_attr(49) <= 0.356) {
                      add_pred(   /* R.3:0.0:1.0:0.0:0.1:0 */
                                 0.9009718459685476);
                    } else {
                      add_pred(   /* R.3:0.0:1.0:0.0:0.1:1 */
                                 -1.0495919406572607);
                    }
                  }
                } else {
                  add_pred(   /* R.3:0.0:1.0:0.0:1 */
                             -2.309123814682225);
                }
              }
            } else {
              add_pred(   /* R.3:0.0:1.0:1 */
                         -1.7943880548046893);
              if (defined_attr(54)) {  /* R.3:0.0:1.0:1.0 */
                if (double_attr(54) <= 2.8095) {
                  add_pred(   /* R.3:0.0:1.0:1.0:0 */
                             -1.8381895819346192);
                } else {
                  add_pred(   /* R.3:0.0:1.0:1.0:1 */
                             1.652206421296063);
                }
              }
            }
          }
        }
      }
    } else {
      add_pred(   /* R.3:1 */
                 2.531462546142542);
    }
  }
  if (defined_attr(26)) {  /* R.4 */
    if (double_attr(26) <= 0.0050) {
      add_pred(   /* R.4:0 */
                 -0.02206661652849869);
    } else {
      add_pred(   /* R.4:1 */
                 1.5751017369924174);
    }
  }

  return finalize_pred();
}

